export interface InventoryDB {
  id: number;
  shop_id: number;
  title: string;
  warehouse_id: string | null;
  product_id: number;
  brand: string | null;
  supplier_id: string | null;
  sku: string;
  condition: string;
  condition_note: string | null;
  description: string | null;
  key_features: string | null;
  stock_quantity: number;
  damaged_quantity: string | null;
  user_id: number;
  purchase_price: string | null;
  sale_price: number;
  offer_price: number | null;
  offer_start: Date | null;
  offer_end: Date | null;
  shipping_weight: number | null;
  free_shipping: boolean;
  available_from: Date;
  min_order_quantity: number;
  slug: string;
  linked_items: string | null;
  meta_title: string | null;
  meta_description: string | null;
  stuff_pick: string | null;
  active: number;
  deleted_at: Date;
  created_at: Date;
  updated_at: Date;
  customer_points_discount_percentage: number;
}

export interface InventoryTezos {
  id: number;
  shopID: number;
  title: string;
  warehouseID: string | null;
  productID: number;
  brand: string | null;
  supplierID: string | null;
  sku: string;
  condition: string;
  conditionNote: string | null;
  description: string | null;
  keyFeatures: string | null;
  stockQuantity: number;
  damagedQuantity: string | null;
  userID: number;
  purchasePrice: string | null;
  salePrice: number;
  offerPrice: number | null;
  offerStart: Date | null;
  offerEnd: Date | null;
  shippingWeight: number | null;
  freeShipping: boolean | null;
  availableFrom: Date;
  minOrderQuantity: number;
  slug: string;
  linkedItems: string | null;
  metaTitle: string | null;
  metaDescription: string | null;
  stuffPick: string | null;
  active: number;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  customerPointsDiscountPercentage: number;
}
